### ISSUE TITLE
When Go 1.9 is released update .travis.yml

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#105]
#102 began to use Go 1.9rc1 for it's ignoring `vendor/` directory features, once go 1.9 is released, change the Go version to 1.x again.

**Comment by shurcooL** [comment]
This is not completely resolved. See https://travis-ci.org/bradleyfalzon/gopherci/builds/268228616?utm_source=github_status&utm_medium=notification. It used Go 1.8.3.

First, Travis needs to be updated so that "1.x" matches 1.9 rather than 1.8.3. They have a table of values hardcoded somewhere. It's a trivial change to make.

**Comment by shurcooL** [comment]
Or maybe that has since changed in https://github.com/travis-ci/travis-build/pull/1094.

**Comment by shurcooL** [comment]
See travis-ci/travis-build#961 for an old PR showing how it was done in the past.

**Comment by shurcooL** [comment]
Looks like there's an open PR at https://github.com/travis-ci/travis-build/pull/1148, so you just need to wait for that to be merged.
