### ISSUE TITLE
Add unconvert tool.

### ISSUE THREAD

**Issue by shurcooL** [bradleyfalzon/gopherci#127]
This is a proposal to add the `unconvert` tool by @mdempsky to GopherCI:

https://github.com/mdempsky/unconvert

I think it's helpful, produces accurate results, and fits in well next to `unused` and `unparam` that GopherCI already supports.

I've been using it locally on all my work over the course of the last 6+ months or so, and I'm happy with it.

(Hopefully this is a less controversial change suggestion than #103; if it gets approval, I'd like to work on it, if no one else wants to take it.)

**Comment by bradleyfalzon** [comment]
Hi @shurcooL 

Firstly, my apologies for the delays, I wanted to push 04f19c3b8bfc14f924cb29810c08b6a639845f07 but I've been busier than I'd have liked, so it was delayed a little. Thanks for being patient.

As for `unconvert`, it's a great addition because it should have little to no false positives, whilst we wait for #8 to be resolved it's going to run for everyone each time.

Check out the `CONTRIBUTING.md` file for some more instructions if you're still keen to give it a try, if not, it's very straightforward for me to do it too.

**Comment by shurcooL** [comment]
Thanks! I'll take it.

**Comment by shurcooL** [comment]
Sorry for the delay. An update here; I now wish to withdraw from taking this and will happily let you take it.

When I was considering working on this, I didn't think about the fact there'd be more than just updating .go code, which is the part I wanted to do. The CONTRIBUTING.md file is very clear and makes me understand what needs to be done, which is dealing with Docker, SQL migrations, etc. In other words, I underestimated the difficulty and scope.

**Comment by bradleyfalzon** [comment]
No issues at all, I can take this one easily.

**Comment by bradleyfalzon** [comment]
OK, I've updated the gopherci-env image and added the migration, tests pass and manually running the tool works a treat on production.

Thanks for the issue @shurcooL!
