### ISSUE TITLE
GopherCI fails with an Internal error when there's missing cgo dependencies

### ISSUE THREAD

**Issue by shurcooL** [bradleyfalzon/gopherci#91]
I did a `git push` with 3 new commits to `master` of https://github.com/shurcooL/cmd:

![image](https://cloud.githubusercontent.com/assets/1924134/25553088/97dc9266-2c78-11e7-8cba-c66b6165b17f.png)

And got a 500 from GopherCI:

![image](https://cloud.githubusercontent.com/assets/1924134/25553094/b8a36d94-2c78-11e7-96a8-1a6c94eac48b.png)

The description is "Could not get VCS".

https://gci.gopherci.io/analysis/319

Reporting this in case it's helpful. Feel free to close otherwise.

**Comment by bradleyfalzon** [comment]
Thanks @shurcooL 

```
Apr 29 14:37:22 www1 gopherci[2792]: 2017/04/29 14:37:22 queueProcessor: processing error: cannot analyse push event for sha 844accfd52e9b4abe20d858de5490c38ae78293f on repo https://github.com/shurcooL/cmd: could not run analyser: could not execute [install-deps.sh]: [install-deps.sh] returned exit code 2
Apr 29 14:37:22 www1 gopherci[2792]: No (or unsupported) vendoring tool, using go get
Apr 29 14:37:22 www1 gopherci[2792]: # github.com/go-gl/glfw/v3.2/glfw
Apr 29 14:37:22 www1 gopherci[2792]: In file included from ./glfw/src/internal.h:169:0,
Apr 29 14:37:22 www1 gopherci[2792]: from ./glfw/src/context.c:28,
Apr 29 14:37:22 www1 gopherci[2792]: from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
Apr 29 14:37:22 www1 gopherci[2792]: ./glfw/src/x11_platform.h:36:22: fatal error: X11/Xlib.h: No such file or directory
Apr 29 14:37:22 www1 gopherci[2792]: #include <X11/Xlib.h>
Apr 29 14:37:22 www1 gopherci[2792]: ^
Apr 29 14:37:22 www1 gopherci[2792]: compilation terminated.
```

This is because the dependencies cgo needs weren't installed prior. If I install `xorg-dev` and `libgl1-mesa-dev` as defined in the repo's `.travis-ci.yml` install deps works successfully.

Some options, and keen to hear other input

- Detect the use of cgo, don't install deps and mark build as successful with a message `Skipped because cgo is unsupported.`. This would likely be the first step, as the build is currently being marked as failed when it shouldn't.
- Somehow allow the user to define a list of packages to be installed after cloning.

Defining the list of packages to be install could be via:

- `.gopherci.yml` or similar file in the repository. This would be optional and provide per repo customisations. I originally thought this should be a part of a web configuration, but those that have access to configure an installation would only be a small subset of maintainers that would need to install additional packages due to ongoing development. As per #8.
- Detect other CI platform's directives and install those, such as the repo's `.travis-ci.yml` `addons.apt_packages`. This I don't like, it may cause GopherCI to install packages that aren't required at all for GopherCI, but were required for other CI runs.
- Detect a makefile with a target `deps`, and if so, use that to install dependencies. This seems a little inexact, and I think a dotfile would be preferable.

As for detecting cgo (and then gracefully terminating), I'm not sure the best way to do this, are there any easy but correct options?

```
root@a7b6bf3fd525:/go/src/github.com/go-gl/glfw/v3.2/glfw# go list -f '{{ .Imports }}'
[C fmt image image/draw log reflect sync unsafe]
root@a7b6bf3fd525:/go/src/github.com/go-gl/glfw/v3.2/glfw# cd -
/go/src/github.com/shurcooL/cmd
root@a7b6bf3fd525:/go/src/github.com/shurcooL/cmd# go list  -f '{{ join .Deps "\n" }}' ./... | grep C
root@a7b6bf3fd525:/go/src/github.com/shurcooL/cmd# go list  -f '{{ join .CgoFiles "\n" }}' ./...
root@a7b6bf3fd525:/go/src/github.com/shurcooL/cmd# go list -f '{{ .Imports }}' ./... | grep C
root@a7b6bf3fd525:/go/src/github.com/shurcooL/cmd#
```

**Comment by bradleyfalzon** [comment]
Perhaps shim something like this https://github.com/gopherci/importsC and configure the 

Perhaps:
- Change install-deps.sh to use `go get -d -t ./...` instead of `go get -t ./...`, so it doesn't require building.
- After clone, run https://github.com/gopherci/importsC
- If importsC, return early and set the status message to `Skipped because cgo is unsupported.`

**Comment by bradleyfalzon** [comment]
I started implementing the ability to ignore the repository if there are cgo dependencies because I don't have a mechanism to allow you to install these just yet. But it started to get hacky to also set the status message, and to do that cleanly would've required more effort than just supporting installing dependencies like I would eventually.

So I'm thinking of supporting a .gopherci.yml something like:

```
apt_packages:
    - xorg-dev
    - libgl1-mesa-dev
```

I'm concerned that as I update the container the tests run in, that those packages may be removed in the future (currently is debian:jessie based). But I'm happy to ignore that for the moment, and just rely on a version 2 attribute or image attribute if it becomes a problem.

**Comment by shurcooL** [comment]
No time pressure from my side. Thanks.

**Comment by bradleyfalzon** [comment]
@fortytw2 has suggested providing the ability for users to specify their own container to run GopherCI tests in.

I do like this suggestion as it addresses the issue that not all cgo dependencies are available via APT. But he further states there's questionable security issues with this (and additional costs for the hosted versions), and we may add more dependencies to our base docker image but wouldn't be able to use them until all user images had updated to that container too.

For that reason (and I'd already written this change), I won't continue down that path, but it may be the correct longer term solution to handle any remaining edge cases.

**Comment by bradleyfalzon** [comment]
Docs added https://github.com/bradleyfalzon/gopherci/wiki/.gopherci.yml-Syntax

If you're satisfied with this method, I'm happy to close this, else, let me know if you have more feedback.

**Comment by shurcooL** [comment]
Those docs look good to me.

**Comment by bradleyfalzon** [comment]
Thanks @shurcooL considering https://github.com/shurcooL/cmd/pull/6 has been accepted, I'll take this as issue resolved. Let me know if you have more feedback or other issues and thanks again for the issue, it's greatly appreciated.

**Comment by shurcooL** [comment]
@bradleyfalzon I've made a similar change in https://github.com/shurcooL/Hover/commit/6f3928f0f5fa09ccb54a3aec5985e5cfcdcc857c, but GopherCI fails with the same error message as before:

https://gci.gopherci.io/analysis/494

Also, if it really failed to _build_ because of the cgo dependencies, why is the error message "Could not get VCS"? Wouldn't "Could not get VCS" make sense if it failed because a branch/repo was deleted or something?

(Sorry, I posted this message in the wrong place first time.)

**Comment by bradleyfalzon** [comment]
As for this specific failure, it's failing because go get was unable to install dependencies:

```
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:39:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
 #include <X11/Xcursor/Xcursor.h>
                                 ^
compilation terminated.
# github.com/go-gl/gl/v2.1/gl
../../go-gl/gl/v2.1/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
  #include <GL/glx.h>
                     ^
compilation terminated.
```

If I then install `libxcursor-dev` and `mesa-common-dev`, and run go get again:

```
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:42:35: fatal error: X11/extensions/Xrandr.h: No such file or directory
 #include <X11/extensions/Xrandr.h>
                                   ^
compilation terminated.
# github.com/go-gl/gl/v2.1/gl
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
```

Installing `libxrandr-dev` and re-rerunning go get:

```
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:48:37: fatal error: X11/extensions/Xinerama.h: No such file or directory
 #include <X11/extensions/Xinerama.h>
                                     ^
compilation terminated.
# github.com/go-gl/gl/v2.1/gl
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
```

This could go on for a while, so I just installed `xorg-dev` and `libgl1-mesa-dev` which appears to have worked (go get no longer fails).

So I think this is just a case of needing more dependencies.

But, the error handling here by GopherCI is poor, and is actively being addressed in #88, see the comment https://github.com/bradleyfalzon/gopherci/issues/88#issuecomment-302911648 - the third fix paragraph would provide you with the feedback you need to debug any of these issues.

> Also, if it really failed to build because of the cgo dependencies, why is the error message "Could not get VCS"? Wouldn't "Could not get VCS" make sense if it failed because a branch/repo was deleted or something?

Yes, the error message here makes zero sense, it's failing because an analysis doesn't have the before/after ref until the analysis has finished successfully. This is being addressed in https://github.com/bradleyfalzon/gopherci/commit/ce5befab09fc2bca113cfe875c2281cb1dc4ac0c along with a few other changes to handle errors.

I'm sorry about this poor error handling, it's all being addressed now via #88.

Does that answer the issue?

**Comment by shurcooL** [comment]
> Does that answer the issue?

Yes, that answers the issue about poor error handling. I forgot #88 exists and is still open, thanks for pointing me at it.

However, I'm confused why [this](https://github.com/shurcooL/Hover/blob/6f3928f0f5fa09ccb54a3aec5985e5cfcdcc857c/.travis.yml#L3-L4) works, but [this](https://github.com/shurcooL/Hover/blob/6f3928f0f5fa09ccb54a3aec5985e5cfcdcc857c/.gopherci.yml#L1-L2) doesn't.

Why is it that only listing `libgles2-mesa-dev` is sufficient for Travis CI but not GopherCI? Does Travis CI pre-install/assume some starting packages? Or does it recursively install dependencies of mentioned packages while GopherCI doesn't?

**Comment by bradleyfalzon** [comment]
I believe it's just because they run Ubuntu precise (12.04 LTS) whereas GopherCI is based on Go images which is debian jessie (8.7).

I don't think this is a problem per-se, @fortytw2 mentioned in https://github.com/bradleyfalzon/gopherci/issues/91#issuecomment-302075038 that it could be possible to provide users the ability to provide their own images, but it has some issues (outlined in the comment). I mention this because a user may prefer to specify their own base image to keep consistency between their own CI and GopherCI.

Another option may be for GopherCI to provide a couple different base images, such as GopherCI:1-precise. This still has a chicken and egg problem that I think is solvable (currently I run the container then get the .gopherci.yml file via cat, instead I'd need to download .gopherci.yml determine the image, then run the container). This would be more development, but may allow for a better consistency between specifying apt packages, and eventually lead to users being able to run the tools in their own image (required if they need to provide cgo dependencies not available via OS packages).

Thoughts?
